---
core:
  num_workers: 10
inventory:
  plugin: nornir.plugins.inventory.simple.SimpleInventory
  options:
    host_file: "hosts.yaml"
    group_file: "groups.yaml"
    default_file: "defaults.yaml"
